### ISSUE TITLE
Code Compiling but Crasshed without error at SPIFFS.begin

### ISSUE THREAD

**Issue by Myggi** [b0xcat/protocontrol#1]
Hello!
first time publishing an issue in github. i'll try to give as much informations as i can!
Had some problem while trying to execute the code.

**First**,
to make the code compile, I had to change the
`ESP Async WebServer ;(line 32 of platformio.ini) ` to `zeed/ESP Async WebServer `
as _me-no-dev_'s one seems to be using a deprecated command:
in ESP Async WebServer/src/WebAuthentication.cpp:73:  `mbedtls_md5_starts` instead of  `mbedtls_md5_starts_ret`

**This Issue was tried on 2 different esp32:**
esp32 D1 mini (500kB ram, 4MB Flash)
esp32S (4MB Flash 8GB RAM)

**here is the issue**
While the code gets correctly compiled and sent to the ESP32, the execution seems to stop abruptly withont any error message in the monitor as soon as it tried to do the `SPIFFS.begin()` lene 101. : 

_(code of main. cpp for context)_
```
void setup()
{
  esp_log_level_set("*", ESP_LOG_VERBOSE);
  Serial.begin(921600);

  //Init Storage
  if (!SPIFFS.begin())
  {
    Serial.setTimeout(10000);
    Serial.println("Storage Mount Failed. Format? [y/n]");
    while(true) {
      if (Serial.available()) {
        char response = Serial.read();
        if (response == 'y') {
          SPIFFS.format();
          Serial.println("Storage Formatted");
          ESP.restart();
        } else {
          Serial.println("Rebooting...");
          ESP.restart();
        }
      }
    }
  }
```
**I tried:**

1. to comment all the if loop
==> Code executing properly but hosted website empty with only "not found" written on it. Monitor says "favicon.ico not found"
2. to get read of the if and while loop
==> code keeps crashing
3. to add `Serial.setDebugOutput(true)` before the if. 
==> codes keep crashing
4. to comment all code and parts bit by bit
==> seems like all code related to `Max7219painter painter(face);` in main.cpp is correlated to this issue as commenting it instead of the spiffs part in the settup() also solved the execution of the code. but hosted website empty with only "not found" written on it. Monitor says "favicon.ico not found"

**Comment by b0xcat** [comment]
I'll look into this further during the weekend, but I suspect most of these issues are caused because this code was written a while ago and the espressif platform version was not pinned. 

Thanks for the PR in https://github.com/b0xcat/protocontrol/pull/2 :)
